PID-17 #in-progress #comment refactor:
HAMES2-1st-3/MechanumWheelControl pull request #13
Opened 2024-05-12 16:07 UTC by re-ag

[Include t시 서브 디렉토리명 삭제](https://autoever3.atlassian.net/browse/PID-18?atlOrigin=eyJpIjoiYmE2NTBlMTJkZWE3NDYyNmFmZmYwYWNiOWI2NzU3NDMiLCJwIjoiaiJ9)

[ISR_PRIORITY_ASCLIN_TX 에 number 추가](https://autoever3.atlassian.net/browse/PID-19?atlOrigin=eyJpIjoiMDI5YWQwYjgxZmYzNGYwZWI4ZDE2OWM0YTkzMjhmODciLCJwIjoiaiJ9)

[.gitignore 수정](https://autoever3.atlassian.net/browse/PID-21?atlOrigin=eyJpIjoiMzQ1NTg0NjBlNmZhNDE4MzkzOWE3MWE4MWMwOTIxNTYiLCJwIjoiaiJ9)

+) `Driver_Joystick.c`, `Driver_Joystick.h`, `Decision_State.c`, `Decision_State.h` 전체 리팩토링

2024-05-12 16:24 UTC, GeoChoi requested changes
굉장히 많은 일을 하셨군요!! 싹다 갈아엎으셨네요
합격드리겠습니다.

그리고 다음번 refactoring에는 
.gitignore에 MechanumWheelControl/.settings/language.settings.xml 도 추가 시킵시다.

![image](https://github.com/HAMES2-1st-3/MechanumWheelControl/assets/109258000/d5890106-3807-4c92-b05e-5aeae55137f4)

이것도 컴퓨터마다 세팅이 바꿔서 불필요하게 commit에 포함되는 것 같네요
이것만 하긴 좀 번거로우니까 일단 jira에 달아 둘꼐요. 나중에 리펙토링 업무 처리할 때 같이 처리하죠.

https://autoever3.atlassian.net/browse/PID-22

가 아니라 반려 한번 때리고 다시 수정해서 해본다는 의미로 Request change 한번 해볼께
![image](https://github.com/HAMES2-1st-3/MechanumWheelControl/assets/109258000/09a674db-2666-47ce-88fa-8058213bce2c)

2024-05-12 16:26 UTC, GeoChoi commented
.gitignore에 MechanumWheelControl/.settings/language.settings.xml 도 추가 시킵시다.

![image](https://github.com/HAMES2-1st-3/MechanumWheelControl/assets/109258000/bf66ef21-1c23-41ae-98ea-f9ea024d0fe3)

이것도 컴퓨터마다 세팅이 바꿔서 불필요하게 commit에 포함되는 것 같네요

2024-05-13 00:46 UTC, re-ag commented
책임님 수정하여 커밋하였습니다. 다시한번 리뷰 부탁드립니다.

2024-05-13 07:32 UTC, GeoChoi approved these changes
잘했어요!!

2024-05-13 07:33 UTC, merged